apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-rclone.fullname" . }}-configmap
  labels:
{{ include "kube-rclone.labels" . | indent 4 }}
data:
  "rclone.conf": |
  {{- .Values.config | nindent 4 }}
