apiVersion: v1
appVersion: v1.48.0
description: A Helm chart for rclone
name: kube-rclone
version: 0.2.0
keywords:
    - rclone
home: https://rclone.org/
icon: https://rclone.org/img/rclone-16x16.png
sources:
    - https://github.com/kflix-tv/helm-charts
maintainers:
    - name: kilian-tyler